import 'package:converter_hub/core/constant/app_key.dart';

class LanguageConstant {
  static List<Map<String, String>> languageList = [
  { AppKey.code: "hi-IN", AppKey.name : "Hindi (India)",AppKey.flag: "🇮🇳"},
  {AppKey.code: "mai-IN", AppKey.name: "Maithili (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "hr-HR", AppKey.name: "Croatian (Croatia)", AppKey.flag: "🇭🇷"},
  {AppKey.code: "ko-KR", AppKey.name: "Korean (South Korea)", AppKey.flag: "🇰🇷"},
  {AppKey.code: "mr-IN", AppKey.name: "Marathi (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "as-IN", AppKey.name: "Assamese (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "ru-RU", AppKey.name: "Russian (Russia)", AppKey.flag: "🇷🇺"},
  {AppKey.code: "zh-TW", AppKey.name: "Zh-Tw", AppKey.flag: "🇹🇼"},
  {AppKey.code: "hu-HU", AppKey.name: "Hungarian (Hungary)", AppKey.flag: "🇭🇺"},
  {AppKey.code: "sw-KE", AppKey.name: "Swahili (Kenya)", AppKey.flag: "🇰🇪"},
  {AppKey.code: "sd-IN", AppKey.name: "Sd-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "ks-IN", AppKey.name: "Ks-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "th-TH", AppKey.name: "Thai (Thailand)", AppKey.flag: "🇹🇭"},
  {AppKey.code: "doi-IN", AppKey.name: "Dogri (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "ur-PK", AppKey.name: "Urdu (Pakistan)", AppKey.flag: "🇵🇰"},
  {AppKey.code: "nb-NO", AppKey.name: "Norwegian Bokmål (Norway)", AppKey.flag: "🇳🇴"},
  {AppKey.code: "da-DK", AppKey.name: "Danish (Denmark)", AppKey.flag: "🇩🇰"},
  {AppKey.code: "tr-TR", AppKey.name: "Turkish (Türkiye)", AppKey.flag: "🇹🇷"},
  {AppKey.code: "et-EE", AppKey.name: "Estonian (Estonia)", AppKey.flag: "🇪🇪"},
  {AppKey.code: "pt-PT", AppKey.name: "Portuguese (Portugal)", AppKey.flag: "🇵🇹"},
  {AppKey.code: "vi-VN", AppKey.name: "Vietnamese (Vietnam)", AppKey.flag: "🇻🇳"},
  {AppKey.code: "ur-IN", AppKey.name: "Urdu (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "en-US", AppKey.name: "English (United States)", AppKey.flag: "🇺🇸"},
  {AppKey.code: "sat-IN", AppKey.name: "Sat-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "sq-AL", AppKey.name: "Albanian (Albania)", AppKey.flag: "🇦🇱"},
  {AppKey.code: "sv-SE", AppKey.name: "Swedish (Sweden)", AppKey.flag: "🇸🇪"},
  {AppKey.code: "ar", AppKey.name: "Arabic", AppKey.flag: "🏳️"}, 
  {AppKey.code: "sr-RS", AppKey.name: "Sr-Rs", AppKey.flag: "🇷🇸"},
  {AppKey.code: "su-ID", AppKey.name: "Su-Id", AppKey.flag: "🇮🇩"},
  {AppKey.code: "bn-BD", AppKey.name: "Bangla (Bangladesh)", AppKey.flag: "🇧🇩"},
  {AppKey.code: "bs-BA", AppKey.name: "Bs-Ba", AppKey.flag: "🇧🇦"},
  {AppKey.code: "mni-IN", AppKey.name: "Mni-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "gu-IN", AppKey.name: "Gujarati (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "kn-IN", AppKey.name: "Kannada (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "el-GR", AppKey.name: "Greek (Greece)", AppKey.flag: "🇬🇷"},
  {AppKey.code: "he-IL", AppKey.name: "Hebrew (Israel)", AppKey.flag: "🇮🇱"},
  {AppKey.code: "fi-FI", AppKey.name: "Finnish (Finland)", AppKey.flag: "🇫🇮"},
  {AppKey.code: "bn-IN", AppKey.name: "Bangla (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "km-KH", AppKey.name: "Khmer (Cambodia)", AppKey.flag: "🇰🇭"},
  {AppKey.code: "fr-FR", AppKey.name: "French (France)", AppKey.flag: "🇫🇷"},
  {AppKey.code: "uk-UA", AppKey.name: "Ukrainian (Ukraine)", AppKey.flag: "🇺🇦"},
  {AppKey.code: "pa-IN", AppKey.name: "Pa-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "en-AU", AppKey.name: "English (Australia)", AppKey.flag: "🇦🇺"},
  {AppKey.code: "nl-NL", AppKey.name: "Dutch (Netherlands)", AppKey.flag: "🇳🇱"},
  {AppKey.code: "fr-CA", AppKey.name: "French (Canada)", AppKey.flag: "🇨🇦"},
  {AppKey.code: "lv-LV", AppKey.name: "Latvian (Latvia)", AppKey.flag: "🇱🇻"},
  {AppKey.code: "pt-BR", AppKey.name: "Portuguese (Brazil)", AppKey.flag: "🇧🇷"},
  {AppKey.code: "de-DE", AppKey.name: "German (Germany)", AppKey.flag: "🇩🇪"},
  {AppKey.code: "ml-IN", AppKey.name: "Malayalam (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "si-LK", AppKey.name: "Sinhala (Sri Lanka)", AppKey.flag: "🇱🇰"},
  {AppKey.code: "cs-CZ", AppKey.name: "Czech (Czechia)", AppKey.flag: "🇨🇿"},
  {AppKey.code: "is-IS", AppKey.name: "Icelandic (Iceland)", AppKey.flag: "🇮🇸"},
  {AppKey.code: "pl-PL", AppKey.name: "Polish (Poland)", AppKey.flag: "🇵🇱"},
  {AppKey.code: "ca-ES", AppKey.name: "Catalan (Spain)", AppKey.flag: "🇪🇸"},
  {AppKey.code: "sk-SK", AppKey.name: "Slovak (Slovakia)", AppKey.flag: "🇸🇰"},
  {AppKey.code: "it-IT", AppKey.name: "Italian (Italy)", AppKey.flag: "🇮🇹"},
  {AppKey.code: "fil-PH", AppKey.name: "Filipino (Philippines)", AppKey.flag: "🇵🇭"},
  {AppKey.code: "lt-LT", AppKey.name: "Lithuanian (Lithuania)", AppKey.flag: "🇱🇹"},
  {AppKey.code: "ne-NP", AppKey.name: "Nepali (Nepal)", AppKey.flag: "🇳🇵"},
  {AppKey.code: "ms-MY", AppKey.name: "Malay (Malaysia)", AppKey.flag: "🇲🇾"},
  {AppKey.code: "en-NG", AppKey.name: "English (Nigeria)", AppKey.flag: "🇳🇬"},
  {AppKey.code: "nl-BE", AppKey.name: "Dutch (Belgium)", AppKey.flag: "🇧🇪"},
  {AppKey.code: "zh-CN", AppKey.name: "Zh-Cn", AppKey.flag: "🇨🇳"},
  {AppKey.code: "es-ES", AppKey.name: "Spanish (Spain)", AppKey.flag: "🇪🇸"},
  {AppKey.code: "ja-JP", AppKey.name: "Japanese (Japan)", AppKey.flag: "🇯🇵"},
  {AppKey.code: "ta-IN", AppKey.name: "Tamil (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "bg-BG", AppKey.name: "Bulgarian (Bulgaria)", AppKey.flag: "🇧🇬"},
  {AppKey.code: "cy-GB", AppKey.name: "Welsh (United Kingdom)", AppKey.flag: "🇬🇧"},
  {AppKey.code: "or-IN", AppKey.name: "Odia (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "brx-IN", AppKey.name: "Bodo (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "sa-IN", AppKey.name: "Sanskrit (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "yue-HK", AppKey.name: "Yue-Hk", AppKey.flag: "🇭🇰"},
  {AppKey.code: "es-US", AppKey.name: "Spanish (United States)", AppKey.flag: "🇺🇸"},
  {AppKey.code: "en-IN", AppKey.name: "English (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "kok-IN", AppKey.name: "Kok-In", AppKey.flag: "🇮🇳"},
  {AppKey.code: "jv-ID", AppKey.name: "Javanese (Indonesia)", AppKey.flag: "🇮🇩"},
  {AppKey.code: "sl-SI", AppKey.name: "Slovenian (Slovenia)", AppKey.flag: "🇸🇮"},
  {AppKey.code: "id-ID", AppKey.name: "Indonesian (Indonesia)", AppKey.flag: "🇮🇩"},
  {AppKey.code: "te-IN", AppKey.name: "Telugu (India)", AppKey.flag: "🇮🇳"},
  {AppKey.code: "ro-RO", AppKey.name: "Romanian (Romania)", AppKey.flag: "🇷🇴"},
  {AppKey.code: "en-GB", AppKey.name: "English (United Kingdom)", AppKey.flag: "🇬🇧"}
  ];
}
